services:
  mongodb:
    image: mongo:latest
    command: mongod --bind_ip_all
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped

  web:
    build: .
    container_name: django
    environment:
      - DEBUG=True
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_DB_HOST=${MONGO_DB_HOST}
      - MONGO_DB_PORT=${MONGO_DB_PORT}
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    command: >
      bash -c "
        while ! nc -z mongodb 27017; do
          echo 'Aguardando o MongoDB...';
          sleep 2;
        done;
        python manage.py migrate && 
        python manage.py runserver 0.0.0.0:8000
      "
    restart: unless-stopped

volumes:
  mongodb-data: